import { connect } from './cdp.mjs';
const c = await connect();
const j = async (e) => JSON.parse(await c.evaluate(`JSON.stringify(${e})`));
await c.evaluate(`app.workspace.openLinkText('Long note','',false).then(()=>new Promise(r=>setTimeout(r,800)))`);
const state = `(() => { const o=[...document.querySelectorAll('.reading-ruler-overlay')]; return o.map(el=>{ const r=rrBand(el); const h=el.parentElement.getBoundingClientRect(); const cs=getComputedStyle(el); return {cls:el.className, opacity:cs.opacity, vis:cs.visibility, pe:cs.pointerEvents, host:{t:Math.round(h.top),l:Math.round(h.left),w:Math.round(h.width),h:Math.round(h.height)}, band:{t:Math.round(r.top),l:Math.round(r.left),w:Math.round(r.width),h:Math.round(r.height)}, handle:getComputedStyle(el.querySelector('.reading-ruler-handle')).display, viewType: el.closest('.workspace-leaf-content')?.dataset.type}; }); })()`;
console.log('before toggle', JSON.stringify(await j(state)));
console.log('commands', JSON.stringify(await j(`Object.keys(app.commands.commands).filter(k=>k.startsWith('reading-ruler'))`)));
console.log('pin available while off?', await c.evaluate(`!!app.commands.commands['reading-ruler:toggle-pin'].checkCallback(true)`));
await c.evaluate(`app.commands.executeCommandById('reading-ruler:toggle')`);
await c.sleep(400);
console.log('after toggle', JSON.stringify(await j(state)));
const host = (await j(state))[0].host;
const x = host.l + Math.round(host.w/2), y = host.t + 300;
await c.mouse('mouseMoved', x, y - 40); await c.mouse('mouseMoved', x, y);
await c.sleep(200);
const s2 = (await j(state))[0];
console.log('after mouse move to y=', y, JSON.stringify(s2.band), 'bandCentre=', s2.band.t + s2.band.h/2, 'cls=', s2.cls);
console.log('elementFromPoint inside band:', await c.evaluate(`(() => { const e=document.elementFromPoint(${x},${y}); return e.tagName+'.'+e.className; })()`));
console.log('elementFromPoint in dim area:', await c.evaluate(`(() => { const e=document.elementFromPoint(${x},${y+200}); return e.tagName+'.'+e.className; })()`));
await c.screenshot('shot-03-follow.png');
c.close();
