import { connect } from './cdp.mjs';
const c = await connect();
const j = async (e) => JSON.parse(await c.evaluate(`JSON.stringify(${e})`));
const band = () => j(`(() => { const el=document.querySelector('.reading-ruler-overlay'); const r=rrBand(el === document ? undefined : el); return {cls:el.className.replace('reading-ruler-overlay','').trim(), t:Math.round(r.top), h:Math.round(r.height), centre: Math.round(r.top+r.height/2)}; })()`);
const listeners = async (sel) => {
	const { result } = await c.send('Runtime.evaluate', { expression: `document.querySelector('${sel}')` });
	const { listeners } = await c.send('DOMDebugger.getEventListeners', { objectId: result.objectId });
	return listeners.map((l) => l.type).sort().join(',');
};
const cmd = (id) => c.evaluate(`app.commands.executeCommandById('reading-ruler:${id}')`);
const X = 684;
await c.mouse('mouseMoved', X, 300); await c.mouse('mouseMoved', X, 400); await c.sleep(150);
console.log('following      ', JSON.stringify(await band()));
console.log('listeners host (on)     :', await listeners('.reading-ruler-host'));
console.log('listeners handle (on)   :', await listeners('.reading-ruler-handle'));
await cmd('toggle-pin'); await c.sleep(100);
await c.mouse('mouseMoved', X, 600); await c.mouse('mouseMoved', X, 650); await c.sleep(150);
console.log('pinned, moved  ', JSON.stringify(await band()));
console.log('listeners host (pinned) :', await listeners('.reading-ruler-host') || '(none)');
console.log('listeners handle(pinned):', await listeners('.reading-ruler-handle') || '(none)');
await cmd('increase-band-height'); await cmd('increase-band-height'); await c.sleep(150);
console.log('pinned +20     ', JSON.stringify(await band()));
await cmd('toggle-pin'); await c.sleep(100);
await c.mouse('mouseMoved', X, 500); await c.mouse('mouseMoved', X, 520); await c.sleep(150);
console.log('unpinned, moved', JSON.stringify(await band()));
await cmd('decrease-band-height'); await cmd('decrease-band-height'); await c.sleep(100);
await cmd('toggle-pin'); await cmd('toggle'); await c.sleep(300);
console.log('off            ', JSON.stringify(await band()), 'model:', JSON.stringify(await j(`(() => { const m=app.plugins.plugins['reading-ruler']; return null; })()`)));
console.log('listeners host (off)    :', await listeners('.reading-ruler-host') || '(none)');
console.log('thicker while off runs? ', await c.evaluate(`app.commands.executeCommandById('reading-ruler:increase-band-height')`));
await cmd('toggle'); await c.sleep(300);
console.log('on again       ', JSON.stringify(await band()), '(must not be pinned, height 60)');
await c.sleep(700);
console.log('data.json      ', await c.evaluate(`app.vault.adapter.read('.obsidian/plugins/reading-ruler/data.json')`));
c.close();
